service: imdbot

plugins:
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs10.x

functions:
  imdbot-movies-command:
    handler: src/movies-command.handler
    events:
    - http:
        path: movies
        method: post
  imdbot-oauth-verifier:
    handler: src/oauth-verifier.handler
    events:
    - http:
        path: oauth
        method: get

custom:
  prune:
    automatic: true
    includeLayers: true
    number: 1
