service: imdbot

provider:
  name: aws
  runtime: nodejs8.10

functions:
  imdbot-movies-command:
    handler: src/movies-command.handler
    events:
    - http:
        path: movies
        method: post
  imdbot-oauth-verifier:
    handler: src/oauth-verifier.handler
    events:
    - http:
        path: oauth
        method: get
